Added recursiveness, improved parsing, added errorhandling for chapters
TheIceCreamTroll/VolumeToChapterConverter pull request #1
Opened 2022-11-13 14:58 UTC by Arch-Storm

Tested on my system. Seems to work fine. Haven't used Python in quite a while.

2022-11-13 15:00 UTC, Arch-Storm commented
also: chapters can now also be without the 'c' in front

and i added automatic directory structuring by name

2022-11-13 15:04 UTC, Arch-Storm commented
oh and chapters like 001x2 work now

(sry did this all in one swoop this morning)

2022-11-13 18:01 UTC, TheIceCreamTroll requested changes
Love the regex changes! Just need to cleanup the string escapes, and take another look at how we handle sub-folders for recursion

2022-11-13 18:01 UTC, TheIceCreamTroll commented on ExtractChaptersFromVolume.py
> +series_regex = r'^.+?(?= [([{]| v[0-9]+)'
What filenames have you tested this with? None of mine have been able to parse

I assume the series parsing is done to create sub-folders when using `-r`? I'd personally rather go with creating a sub-folder relative to the volume being extracted due to [how complex](https://github.com/Kareadita/Kavita/blob/develop/API/Services/Tasks/Scanner/Parser/Parser.cs) series parsing can get.

I'll add a commit to show what I mean. Lmk what you think of it

2022-11-13 18:01 UTC, TheIceCreamTroll commented on ExtractChaptersFromVolume.py
> +                        print(f"-> There seem to be not chapters in \"{volume_file[1]}\\{volume_file[0]}\". Skipping...")
"not chapters" -> "no chapters"

2022-11-13 18:01 UTC, TheIceCreamTroll commented on ExtractChaptersFromVolume.py
> +                print(f'Creating: \"{chapter_folder}{ext}\"')
The `\` escapes aren't needed

2022-11-13 18:01 UTC, TheIceCreamTroll commented on ExtractChaptersFromVolume.py
> +                        print(f"-> There seem to be not chapters in \"{volume_file[1]}\\{volume_file[0]}\". Skipping...")
~~The \ escapes aren't needed~~ you can just swap the outer double quotes for single quotes

2022-11-13 18:01 UTC, TheIceCreamTroll commented on ExtractChaptersFromVolume.py
> +                    print(f"No chapters found in \"{file}\". Skipping...")
~~The \ escapes aren't needed~~ you can just swap the outer double quotes for single quotes

2022-11-13 18:01 UTC, TheIceCreamTroll commented on ExtractChaptersFromVolume.py
> +            print(f"\nProcessing: \"{volume_file[1]}\\{volume_file[0]}\"")
~~The `\` escapes aren't needed~~ you can just swap the outer double quotes for single quotes

2022-11-13 18:10 UTC, TheIceCreamTroll commented on ExtractChaptersFromVolume.py
> +series_regex = r'^.+?(?= [([{]| v[0-9]+)'
Ah, I don't think "Allow Edits From Maintainers" is checked. Could you enable it?

2022-11-13 19:54 UTC, Arch-Storm commented on ExtractChaptersFromVolume.py
> +series_regex = r'^.+?(?= [([{]| v[0-9]+)'
Allow edits by maintainers was checked and is still checked... Don't know why it's not working for you.

I only used the series name parsing using files structured like this: "Berserk v40 ....cbz" or "Berserk [....cbz". All my cbz's start in one of these ways, but maybe this isn't suitable for the public script.
Also "series" might be a bit misleading: It creates seperate folders per "season", so "Tokyo Ghoul" and "Tokyo Ghoul - re" are seperate folders.

2022-11-13 20:31 UTC, TheIceCreamTroll commented on ExtractChaptersFromVolume.py
> +series_regex = r'^.+?(?= [([{]| v[0-9]+)'
Ah, it was just Git gore on my end. Give my commit a run and lmk what you think

Now that you've explained it, I can see the use case, although I think that the regex too finicky to be the default behavior. "Berserk Vol. 40" and "Berserk Volume 40", for example, are two fairly commonly used cases that fail. If you want to add it as a CLI arg though, to override the default behavior, I wouldn't be against it.

2022-11-14 13:45 UTC, Arch-Storm commented on ExtractChaptersFromVolume.py
> +series_regex = r'^.+?(?= [([{]| v[0-9]+)'
Made the series parsing optional and made the regex way more robust. Lmk if you're happy with this 👍🏻

2022-11-15 01:11 UTC, TheIceCreamTroll commented on ExtractChaptersFromVolume.py
> +series_regex = r'^.+?(?= [([{]| v[0-9]+)'
Perfect! I'll go ahead and merge. Just changed a few of the argparse descriptions to be a bit more clear.

Thanks again for opening this PR. Lots of great improvements!

2022-11-15 01:11 UTC, TheIceCreamTroll approved these changes

2022-11-15 01:14 UTC, merged